#-*- coding=gbk -*-
f = open("jsonpage.py","r")
f_ = f.read()
f.close()
f1 = open("青荇/jsonpage.py","w+")
f1.write(f_)
f1.close()
f1 = open("红莲/jsonpage.py","w+")
f1.write(f_)
f1.close()
f1 = open("白鲸/jsonpage.py","w+")
f1.write(f_)
f1.close()
f1 = open("西琳/jsonpage.py","w+")
f1.write(f_)
f1.close()
